version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    tmpfs:
      - /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d test_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  tests:
    build: .
    environment:
      DATABASE_URL: postgresql://test_user:test_password@db:5432/test_db
      PYTHONPATH: /app
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    command: pytest -v 


  bash:
    build:
      context: .
    command: bash
    stdin_open: true
    tty: true
